test_that("is_path works", {
  expect_true(is_fileext_path(file.path(getwd(), "test.txt"), "txt"))
  expect_true(is_filetype_path(file.path(getwd(), "test.txt"), "txt"))
  expect_true(is_geojson_fileext(file.path(getwd(), "test.geojson")))
  expect_true(is_csv_fileext(file.path(getwd(), "test.csv")))
  expect_true(is_excel_fileext(file.path(getwd(), "test.xlsx")))
  expect_true(is_rdata_fileext(file.path(getwd(), "test.RData")))
  expect_true(is_rds_fileext(file.path(getwd(), "test.rds")))
  expect_true(is_rda_fileext(file.path(getwd(), "test.rda")))
})
